## Gradient Descent - Multivariate GMM

Note:- *not perfectly working yet*

In [2]:
import numpy as np
from tqdm import tqdm 
import matplotlib.pyplot as plt

In [69]:
N = 10
D = 2
K = 3
mu_1, sigma_1 = ( np.array([-4, -5]), np.array([[1, 0], [0, 1]]) )
mu_2, sigma_2 = ( np.array([0, 0]), np.array([[1, 0], [0, 1]]) )
mu_3, sigma_3 = ( np.array([4, 5]), np.array([[1, 0], [0, 1]]) )

priors = [0.2, 0.5, 0.3]

X1 = np.random.multivariate_normal(mean=mu_1, cov=sigma_1, size=int(priors[0]*N))
X2 = np.random.multivariate_normal(mean=mu_2, cov=sigma_2, size=int(priors[1]*N))
X3 = np.random.multivariate_normal(mean=mu_3, cov=sigma_3, size=int(priors[2]*N))
X = np.concatenate((X1, X2, X3))
X1.shape, X2.shape, X3.shape, X.shape

((2, 2), (5, 2), (3, 2), (10, 2))

In [70]:
def pdf(x, mu, covariance):
    """pdf of the multivariate normal distribution."""
    x_m = x - mu
    d = x.shape[-1]
    return (1. / (np.sqrt((2 * np.pi)**d * np.linalg.det(covariance))) * 
            np.exp(-(np.linalg.solve(covariance, x_m).T.dot(x_m)) / 2))

In [71]:
pdf(np.array([0, 0]), mu_2, sigma_2)

0.15915494309189535

In [72]:
X.shape

(10, 2)

In [85]:
lambdas = np.ones((K))/K
lambdas = [0.2, 0.5, 0.3]
means = np.array([np.random.choice(X[:, i], K) for i in range(D)]).transpose(-1, 0) #(K, D)
covariances = np.array([np.identity(D)/K for _ in range(K)])
covariances = np.array([sigma_1, sigma_2, sigma_3])
print('Means: ', means, '\n\n', 'Cov: ', covariances, '\n\n', 'Lambdas: ', lambdas)

Means:  [[ 0.92656945 -0.82103822]
 [ 3.48680463 -4.95400964]
 [ 0.92656945 -0.06200216]] 

 Cov:  [[[1 0]
  [0 1]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 1]]] 

 Lambdas:  [0.2, 0.5, 0.3]


In [86]:
covariances.shape

(3, 2, 2)

In [91]:
for iteration in range(1000):
    G = np.zeros((K, N)) #Gamma
    for k in range(K):
        G[k, :] = np.array([pdf(X_i, means[k], covariances[k]) * lambdas[k] for X_i in X])
    # print('G', G)
    # print('sum', np.sum(G, axis=0))
    G = G / np.sum(G, axis=0)
    
    for k in range(K):
        #Mean derivative
        cov_inv = np.linalg.inv(covariances[k]) # (d, d)
        cov_inv_x_minus_mu = np.matmul(cov_inv, (X - means[k]).T).transpose(1, 0) # (n, d)
        derivative_mean = np.matmul(G[k, :], cov_inv_x_minus_mu)
        
        
        # numerator = np.zeros((D, D))
        # for i in range(N):
        #     cov_inv = np.linalg.inv(covariances[k])
        #     numerator += G[k, i] * (cov_inv @ (X[i] - means[k]).reshape(D, 1) @ (X[i] - means[k]).reshape(1, D) @ cov_inv) - cov_inv
        # derivative_sigma = 1/2 * numerator

        means[k] = means[k] + (0.001 * derivative_mean)
        # covariances[k] = covariances[k] - derivative_sigma
    print(f'Iteration {iteration}: \nmeans - {means}, \nvariances - {covariances}, \nlambdas = {lambdas}\n')

print(f'Results\n: means - {means}, \nvariances - {covariances}, \nlambdas = {lambdas}\n')

Streaming output truncated to the last 5000 lines.
lambdas = [0.2, 0.5, 0.3]

Iteration 644: 
means - [[-3.71127682 -5.42737718]
 [ 3.38355582 -4.96555612]
 [ 2.30588743  1.56443128]], 
variances - [[[1 0]
  [0 1]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 1]]], 
lambdas = [0.2, 0.5, 0.3]

Iteration 645: 
means - [[-3.7115016  -5.42760603]
 [ 3.38355397 -4.96555282]
 [ 2.30588743  1.56443129]], 
variances - [[[1 0]
  [0 1]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 1]]], 
lambdas = [0.2, 0.5, 0.3]

Iteration 646: 
means - [[-3.71172593 -5.42783442]
 [ 3.38355213 -4.96554952]
 [ 2.30588743  1.56443129]], 
variances - [[[1 0]
  [0 1]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 1]]], 
lambdas = [0.2, 0.5, 0.3]

Iteration 647: 
means - [[-3.71194981 -5.42806235]
 [ 3.38355029 -4.96554623]
 [ 2.30588743  1.56443129]], 
variances - [[[1 0]
  [0 1]]

 [[1 0]
  [0 1]]

 [[1 0]
  [0 1]]], 
lambdas = [0.2, 0.5, 0.3]

Iteration 648: 
means - [[-3.71217324 -5.42828983]
 [ 3.38354844 -4.96554293]
 [ 2.30588743  1.56443129]], 
va